-- ATENÇÃO: este script APAGA as tabelas antigas e seus dados.
-- Use-o somente para criar a base novamente do zero.

begin;

-- Remove objetos da versão em português, caso já existam.
drop view if exists public.vw_requisicoes_administrativo cascade;
drop view if exists public.vw_pendencias_est_operador cascade;
drop view if exists public.vw_progresso_requisicoes cascade;
drop function if exists public.registrar_entrega(bigint, numeric, text, text);
drop function if exists public.importar_email(jsonb, jsonb, jsonb);
drop table if exists public.apontamentos_entrega cascade;
drop table if exists public.itens_resumo_totvs cascade;
drop table if exists public.itens_requisicao cascade;
drop table if exists public.importacoes_email cascade;

-- Remove também os objetos da versão antiga em inglês.
drop view if exists public.vw_admin_requests cascade;
drop view if exists public.vw_operator_pending_est cascade;
drop view if exists public.vw_request_progress cascade;
drop function if exists public.register_delivery(bigint, numeric, text, text);
drop function if exists public.import_email(jsonb, jsonb, jsonb);
drop table if exists public.delivery_entries cascade;
drop table if exists public.totvs_summary_items cascade;
drop table if exists public.request_items cascade;
drop table if exists public.email_imports cascade;

create table public.importacoes_email (
    id bigint generated by default as identity primary key,

    hash_arquivo text not null unique,
    nome_arquivo text not null,

    assunto text,
    remetente text,
    recebido_em timestamptz,

    local_estoque text,
    tipo_movimento text,

    quantidade_detalhes integer not null default 0,
    quantidade_resumos integer not null default 0,

    peso_detalhes numeric(14, 3) not null default 0,
    peso_resumos numeric(14, 3) not null default 0,

    importado_por text,
    importado_em timestamptz not null default now()
);

create table public.itens_requisicao (
    id bigint generated by default as identity primary key,

    importacao_email_id bigint not null
        references public.importacoes_email(id)
        on delete cascade,

    tipo_material text not null,
    local_estoque text not null,

    material text,
    dimensao text,
    quantidade numeric(14, 3) not null default 0,

    rastreabilidade text,
    data_requisicao date,
    maquina text,
    localizacao text,
    setor text,

    peso_material_kg numeric(14, 3),
    peso_requisitado_kg numeric(14, 3),

    indice_tabela_origem integer,
    indice_linha_origem integer
);

create table public.itens_resumo_totvs (
    id bigint generated by default as identity primary key,

    importacao_email_id bigint not null
        references public.importacoes_email(id)
        on delete cascade,

    tipo_material text not null,
    local_estoque text not null,

    numero_requisicao text,
    material text,
    os_so text,
    numero_of text,

    peso_material_kg numeric(14, 3),
    peso_requisitado_kg numeric(14, 3),

    indice_tabela_origem integer,
    indice_linha_origem integer
);

create table public.apontamentos_entrega (
    id bigint generated by default as identity primary key,

    item_requisicao_id bigint not null
        references public.itens_requisicao(id)
        on delete cascade,

    quantidade_entregue numeric(14, 3) not null
        check (quantidade_entregue > 0),

    nome_operador text not null,
    observacao text,
    entregue_em timestamptz not null default now()
);

create index idx_itens_requisicao_importacao
    on public.itens_requisicao(importacao_email_id);

create index idx_itens_requisicao_material
    on public.itens_requisicao(material);

create index idx_itens_requisicao_data
    on public.itens_requisicao(data_requisicao);

create index idx_itens_resumo_importacao
    on public.itens_resumo_totvs(importacao_email_id);

create index idx_itens_resumo_requisicao
    on public.itens_resumo_totvs(numero_requisicao);

create index idx_apontamentos_item
    on public.apontamentos_entrega(item_requisicao_id);

create index idx_apontamentos_data
    on public.apontamentos_entrega(entregue_em);

-- Uma única chamada grava o e-mail e todas as linhas na mesma transação.
create or replace function public.importar_email(
    p_email jsonb,
    p_itens_requisicao jsonb,
    p_itens_resumo jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_importacao_id bigint;
    v_id_existente bigint;
    v_quantidade_detalhes integer;
    v_quantidade_resumos integer;
    v_peso_detalhes numeric(14, 3);
    v_peso_resumos numeric(14, 3);
begin
    insert into public.importacoes_email (
        hash_arquivo,
        nome_arquivo,
        assunto,
        remetente,
        recebido_em,
        local_estoque,
        tipo_movimento,
        importado_por
    )
    values (
        p_email->>'hash_arquivo',
        p_email->>'nome_arquivo',
        p_email->>'assunto',
        p_email->>'remetente',
        nullif(p_email->>'recebido_em', '')::timestamptz,
        p_email->>'local_estoque',
        p_email->>'tipo_movimento',
        p_email->>'importado_por'
    )
    on conflict (hash_arquivo) do nothing
    returning id into v_importacao_id;

    if v_importacao_id is null then
        select id
          into v_id_existente
          from public.importacoes_email
         where hash_arquivo = p_email->>'hash_arquivo';

        return jsonb_build_object(
            'status', 'DUPLICADO',
            'importacao_id', v_id_existente
        );
    end if;

    insert into public.itens_requisicao (
        importacao_email_id,
        tipo_material,
        local_estoque,
        material,
        dimensao,
        quantidade,
        rastreabilidade,
        data_requisicao,
        maquina,
        localizacao,
        setor,
        peso_material_kg,
        peso_requisitado_kg,
        indice_tabela_origem,
        indice_linha_origem
    )
    select
        v_importacao_id,
        x.tipo_material,
        x.local_estoque,
        x.material,
        x.dimensao,
        x.quantidade,
        x.rastreabilidade,
        nullif(x.data_requisicao, '')::date,
        x.maquina,
        x.localizacao,
        x.setor,
        x.peso_material_kg,
        x.peso_requisitado_kg,
        x.indice_tabela_origem,
        x.indice_linha_origem
    from jsonb_to_recordset(coalesce(p_itens_requisicao, '[]'::jsonb)) as x(
        tipo_material text,
        local_estoque text,
        material text,
        dimensao text,
        quantidade numeric,
        rastreabilidade text,
        data_requisicao text,
        maquina text,
        localizacao text,
        setor text,
        peso_material_kg numeric,
        peso_requisitado_kg numeric,
        indice_tabela_origem integer,
        indice_linha_origem integer
    );

    insert into public.itens_resumo_totvs (
        importacao_email_id,
        tipo_material,
        local_estoque,
        numero_requisicao,
        material,
        os_so,
        numero_of,
        peso_material_kg,
        peso_requisitado_kg,
        indice_tabela_origem,
        indice_linha_origem
    )
    select
        v_importacao_id,
        x.tipo_material,
        x.local_estoque,
        x.numero_requisicao,
        x.material,
        x.os_so,
        x.numero_of,
        x.peso_material_kg,
        x.peso_requisitado_kg,
        x.indice_tabela_origem,
        x.indice_linha_origem
    from jsonb_to_recordset(coalesce(p_itens_resumo, '[]'::jsonb)) as x(
        tipo_material text,
        local_estoque text,
        numero_requisicao text,
        material text,
        os_so text,
        numero_of text,
        peso_material_kg numeric,
        peso_requisitado_kg numeric,
        indice_tabela_origem integer,
        indice_linha_origem integer
    );

    select count(*), coalesce(sum(peso_requisitado_kg), 0)
      into v_quantidade_detalhes, v_peso_detalhes
      from public.itens_requisicao
     where importacao_email_id = v_importacao_id;

    select count(*), coalesce(sum(peso_requisitado_kg), 0)
      into v_quantidade_resumos, v_peso_resumos
      from public.itens_resumo_totvs
     where importacao_email_id = v_importacao_id;

    update public.importacoes_email
       set quantidade_detalhes = v_quantidade_detalhes,
           quantidade_resumos = v_quantidade_resumos,
           peso_detalhes = v_peso_detalhes,
           peso_resumos = v_peso_resumos
     where id = v_importacao_id;

    return jsonb_build_object(
        'status', 'IMPORTADO',
        'importacao_id', v_importacao_id,
        'quantidade_detalhes', v_quantidade_detalhes,
        'quantidade_resumos', v_quantidade_resumos,
        'peso_detalhes', v_peso_detalhes,
        'peso_resumos', v_peso_resumos
    );
end;
$$;

create or replace view public.vw_progresso_requisicoes as
select
    ir.id as item_requisicao_id,
    ir.importacao_email_id,
    ir.tipo_material,
    ir.local_estoque,
    ir.material,
    ir.dimensao,
    ir.quantidade as quantidade_solicitada,
    coalesce(entrega.quantidade_entregue, 0)::numeric(14, 3)
        as quantidade_entregue,
    greatest(
        ir.quantidade - coalesce(entrega.quantidade_entregue, 0),
        0
    )::numeric(14, 3) as quantidade_restante,
    case
        when ir.local_estoque = 'FAB' then 'NAO_REQUER_ENTREGA'
        when ir.quantidade - coalesce(entrega.quantidade_entregue, 0) <= 0
            then 'ENTREGUE'
        when coalesce(entrega.quantidade_entregue, 0) > 0 then 'PARCIAL'
        else 'PENDENTE'
    end as status_entrega,
    ir.rastreabilidade,
    ir.data_requisicao,
    ir.maquina,
    ir.localizacao,
    ir.setor,
    ir.peso_material_kg,
    ir.peso_requisitado_kg,
    case
        when ir.local_estoque = 'EST'
         and ir.quantidade - coalesce(entrega.quantidade_entregue, 0) <= 0
            then entrega.ultima_entrega_em
        else null
    end as concluido_em,
    ie.nome_arquivo as nome_arquivo_email,
    ie.assunto as assunto_email,
    ie.recebido_em as recebido_em_email,
    ie.tipo_movimento
from public.itens_requisicao ir
join public.importacoes_email ie
  on ie.id = ir.importacao_email_id
left join lateral (
    select
        coalesce(sum(ae.quantidade_entregue), 0) as quantidade_entregue,
        max(ae.entregue_em) as ultima_entrega_em
    from public.apontamentos_entrega ae
    where ae.item_requisicao_id = ir.id
) entrega on true;

create or replace view public.vw_pendencias_est_operador as
select *
from public.vw_progresso_requisicoes
where local_estoque = 'EST'
  and quantidade_restante > 0;

create or replace view public.vw_requisicoes_administrativo as
select *
from public.vw_progresso_requisicoes
where local_estoque = 'FAB'
   or (local_estoque = 'EST' and quantidade_restante <= 0);

-- O bloqueio FOR UPDATE impede que dois operadores excedam a quantidade.
create or replace function public.registrar_entrega(
    p_item_requisicao_id bigint,
    p_quantidade numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_solicitada numeric(14, 3);
    v_quantidade_entregue numeric(14, 3);
    v_quantidade_restante numeric(14, 3);
    v_apontamento_id bigint;
begin
    if p_quantidade is null or p_quantidade <= 0 then
        raise exception 'A quantidade entregue deve ser maior que zero.';
    end if;

    if nullif(trim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select quantidade
      into v_quantidade_solicitada
      from public.itens_requisicao
     where id = p_item_requisicao_id
       and local_estoque = 'EST'
     for update;

    if not found then
        raise exception 'Item EST não encontrado.';
    end if;

    select coalesce(sum(quantidade_entregue), 0)
      into v_quantidade_entregue
      from public.apontamentos_entrega
     where item_requisicao_id = p_item_requisicao_id;

    v_quantidade_restante := v_quantidade_solicitada - v_quantidade_entregue;

    if v_quantidade_restante <= 0 then
        raise exception 'Este item já foi totalmente entregue.';
    end if;

    if p_quantidade > v_quantidade_restante then
        raise exception
            'A quantidade informada (%) é maior que a quantidade restante (%).',
            p_quantidade,
            v_quantidade_restante;
    end if;

    insert into public.apontamentos_entrega (
        item_requisicao_id,
        quantidade_entregue,
        nome_operador,
        observacao
    )
    values (
        p_item_requisicao_id,
        p_quantidade,
        trim(p_nome_operador),
        nullif(trim(p_observacao), '')
    )
    returning id into v_apontamento_id;

    v_quantidade_restante := v_quantidade_restante - p_quantidade;

    return jsonb_build_object(
        'status', 'REGISTRADO',
        'apontamento_id', v_apontamento_id,
        'item_requisicao_id', p_item_requisicao_id,
        'quantidade_entregue', p_quantidade,
        'quantidade_restante', v_quantidade_restante
    );
end;
$$;

-- Modo simplificado: chave publicável/anon, sem login.
grant usage on schema public to anon, authenticated;

alter table public.importacoes_email disable row level security;
alter table public.itens_requisicao disable row level security;
alter table public.itens_resumo_totvs disable row level security;
alter table public.apontamentos_entrega disable row level security;

grant select, insert, update, delete
    on public.importacoes_email to anon, authenticated;
grant select, insert, update, delete
    on public.itens_requisicao to anon, authenticated;
grant select, insert, update, delete
    on public.itens_resumo_totvs to anon, authenticated;
grant select, insert, update, delete
    on public.apontamentos_entrega to anon, authenticated;

grant select on public.vw_progresso_requisicoes to anon, authenticated;
grant select on public.vw_pendencias_est_operador to anon, authenticated;
grant select on public.vw_requisicoes_administrativo to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.importar_email(jsonb, jsonb, jsonb)
    to anon, authenticated;
grant execute on function public.registrar_entrega(bigint, numeric, text, text)
    to anon, authenticated;

commit;
