-- ============================================================================
-- GERENCIAL ALMOX - RECRIAÇÃO COMPLETA DO BANCO
-- Compatível com a aplicação após os ajustes de Materiais em Fábrica.
--
-- ATENÇÃO:
--   Este script APAGA todos os dados e recria tabelas, views, índices e RPCs.
--   Execute o arquivo inteiro no SQL Editor do Supabase.
--   Todo o processo ocorre em uma transação: se houver erro antes do COMMIT,
--   o PostgreSQL desfaz as alterações desta execução.
-- ============================================================================

begin;

-- ============================================================================
-- 1. REMOÇÃO DOS OBJETOS ATUAIS E DE VERSÕES ANTERIORES
-- ============================================================================

-- Views atuais.
drop view if exists public.vw_historico_devolucoes cascade;
drop view if exists public.vw_materiais_fabrica cascade;
drop view if exists public.vw_historico_entregas cascade;
drop view if exists public.vw_requisicoes_administrativo cascade;
drop view if exists public.vw_pendencias_est_operador cascade;
drop view if exists public.vw_progresso_requisicoes cascade;

-- Views de versões antigas em inglês.
drop view if exists public.vw_admin_requests cascade;
drop view if exists public.vw_operator_pending_est cascade;
drop view if exists public.vw_request_progress cascade;

-- Funções atuais.
drop function if exists public.devolver_material(bigint, numeric, text, text) cascade;
drop function if exists public.ajustar_material_fabrica(bigint, numeric, text, text) cascade;
drop function if exists public.registrar_entrega_mista(bigint, numeric, text, text) cascade;
drop function if exists public.registrar_entrega_material_fabrica(bigint, numeric, text, text) cascade;
drop function if exists public.consultar_material_fabrica(bigint) cascade;
drop function if exists public.registrar_entrega(bigint, numeric, text, text) cascade;
drop function if exists public.fn_quantidade_entregue_liquida(bigint) cascade;
drop function if exists public.fn_chave_material(text) cascade;
drop function if exists public.importar_email(jsonb, jsonb, jsonb) cascade;

-- Funções de versões antigas em inglês.
drop function if exists public.register_delivery(bigint, numeric, text, text) cascade;
drop function if exists public.import_email(jsonb, jsonb, jsonb) cascade;

-- Tabelas atuais. A lista conjunta permite remover as dependências entre elas.
drop table if exists
    public.ajustes_materiais_fabrica,
    public.consumos_materiais_fabrica,
    public.lotes_materiais_fabrica,
    public.devolucoes_entrega,
    public.apontamentos_entrega,
    public.itens_resumo_totvs,
    public.itens_requisicao,
    public.importacoes_email
cascade;

-- Tabelas de versões antigas em inglês.
drop table if exists
    public.delivery_entries,
    public.totvs_summary_items,
    public.request_items,
    public.email_imports
cascade;

-- ============================================================================
-- 2. TABELAS PRINCIPAIS
-- ============================================================================

create table public.importacoes_email (
    id bigint generated by default as identity primary key,

    hash_arquivo text not null unique,
    nome_arquivo text not null,

    assunto text,
    remetente text,
    recebido_em timestamptz,

    local_estoque text,
    tipo_movimento text,

    quantidade_detalhes integer not null default 0
        check (quantidade_detalhes >= 0),
    quantidade_resumos integer not null default 0
        check (quantidade_resumos >= 0),

    peso_detalhes numeric(14, 3) not null default 0,
    peso_resumos numeric(14, 3) not null default 0,

    importado_por text,
    importado_em timestamptz not null default now()
);

create table public.itens_requisicao (
    id bigint generated by default as identity primary key,

    importacao_email_id bigint not null
        references public.importacoes_email(id)
        on delete cascade,

    tipo_material text not null,
    local_estoque text not null,

    material text,
    dimensao text,
    quantidade numeric(14, 3) not null default 0
        check (quantidade >= 0),

    rastreabilidade text,
    data_requisicao date,
    maquina text,
    localizacao text,
    setor text,

    peso_material_kg numeric(14, 3),
    peso_requisitado_kg numeric(14, 3),

    indice_tabela_origem integer,
    indice_linha_origem integer
);

create table public.itens_resumo_totvs (
    id bigint generated by default as identity primary key,

    importacao_email_id bigint not null
        references public.importacoes_email(id)
        on delete cascade,

    tipo_material text not null,
    local_estoque text not null,

    numero_requisicao text,
    material text,
    os_so text,
    numero_of text,

    peso_material_kg numeric(14, 3),
    peso_requisitado_kg numeric(14, 3),

    indice_tabela_origem integer,
    indice_linha_origem integer
);

create table public.apontamentos_entrega (
    id bigint generated by default as identity primary key,

    item_requisicao_id bigint not null
        references public.itens_requisicao(id)
        on delete cascade,

    -- Quantidade efetivamente aplicada à requisição.
    quantidade_entregue numeric(14, 3) not null
        check (quantidade_entregue > 0),

    -- Quantidade que ultrapassou o restante da requisição e foi para a fábrica.
    quantidade_excedente numeric(14, 3) not null default 0
        check (quantidade_excedente >= 0),

    -- NOVO: saiu do estoque do operador.
    -- FABRICA: foi reaproveitado do saldo existente na fábrica.
    origem_entrega text not null default 'NOVO'
        check (origem_entrega in ('NOVO', 'FABRICA')),

    nome_operador text not null,
    observacao text,
    entregue_em timestamptz not null default now()
);

create table public.devolucoes_entrega (
    id bigint generated by default as identity primary key,

    apontamento_entrega_id bigint not null
        references public.apontamentos_entrega(id)
        on delete cascade,

    quantidade_devolvida numeric(14, 3) not null
        check (quantidade_devolvida > 0),

    nome_operador text not null,
    observacao text,
    devolvido_em timestamptz not null default now()
);

-- Cada excedente criado por uma entrega normal gera um lote individual.
create table public.lotes_materiais_fabrica (
    id bigint generated by default as identity primary key,

    apontamento_origem_id bigint not null unique
        references public.apontamentos_entrega(id)
        on delete cascade,

    material text not null,
    material_chave text not null,

    rastreabilidade text not null,
    rastreabilidade_chave text not null,

    quantidade_inicial numeric(14, 3) not null
        check (quantidade_inicial > 0),

    -- Pode ser maior que a inicial após ajuste manual; nunca pode ser negativa.
    quantidade_disponivel numeric(14, 3) not null
        check (quantidade_disponivel >= 0),

    nome_operador text not null,
    recebido_em timestamptz not null default now()
);

-- Relaciona uma entrega de origem FABRICA aos lotes efetivamente consumidos.
create table public.consumos_materiais_fabrica (
    id bigint generated by default as identity primary key,

    lote_material_fabrica_id bigint not null
        references public.lotes_materiais_fabrica(id),

    apontamento_destino_id bigint not null
        references public.apontamentos_entrega(id)
        on delete cascade,

    quantidade_consumida numeric(14, 3) not null
        check (quantidade_consumida > 0),

    quantidade_estornada numeric(14, 3) not null default 0
        check (
            quantidade_estornada >= 0
            and quantidade_estornada <= quantidade_consumida
        ),

    nome_operador text not null,
    consumido_em timestamptz not null default now()
);

-- Auditoria de alterações manuais e zeramentos automáticos dos lotes.
create table public.ajustes_materiais_fabrica (
    id bigint generated by default as identity primary key,

    lote_material_fabrica_id bigint not null
        references public.lotes_materiais_fabrica(id)
        on delete cascade,

    quantidade_anterior numeric(14, 3) not null,
    quantidade_nova numeric(14, 3) not null
        check (quantidade_nova >= 0),
    diferenca numeric(14, 3) not null,

    nome_operador text not null,
    observacao text,
    motivo text not null default 'AJUSTE_MANUAL',
    ajustado_em timestamptz not null default now()
);

-- ============================================================================
-- 3. ÍNDICES
-- ============================================================================

create index idx_itens_requisicao_importacao
    on public.itens_requisicao(importacao_email_id);

create index idx_itens_requisicao_material_rastreabilidade
    on public.itens_requisicao(material, rastreabilidade);

create index idx_itens_requisicao_data
    on public.itens_requisicao(data_requisicao);

create index idx_itens_resumo_importacao
    on public.itens_resumo_totvs(importacao_email_id);

create index idx_itens_resumo_requisicao
    on public.itens_resumo_totvs(numero_requisicao);

create index idx_apontamentos_item
    on public.apontamentos_entrega(item_requisicao_id);

create index idx_apontamentos_data
    on public.apontamentos_entrega(entregue_em);

create index idx_devolucoes_apontamento
    on public.devolucoes_entrega(apontamento_entrega_id);

create index idx_devolucoes_data
    on public.devolucoes_entrega(devolvido_em);

create index idx_lotes_fabrica_chaves
    on public.lotes_materiais_fabrica(
        material_chave,
        rastreabilidade_chave,
        recebido_em,
        id
    );

create index idx_lotes_fabrica_disponivel
    on public.lotes_materiais_fabrica(quantidade_disponivel)
    where quantidade_disponivel > 0;

create index idx_consumos_fabrica_destino
    on public.consumos_materiais_fabrica(apontamento_destino_id);

create index idx_consumos_fabrica_lote
    on public.consumos_materiais_fabrica(lote_material_fabrica_id);

create index idx_ajustes_fabrica_lote
    on public.ajustes_materiais_fabrica(lote_material_fabrica_id);

-- ============================================================================
-- 4. FUNÇÕES AUXILIARES
-- ============================================================================

-- Normaliza a combinação Material x Rastreabilidade.
create function public.fn_chave_material(p_valor text)
returns text
language sql
immutable
set search_path = public
as $$
    select upper(
        regexp_replace(
            btrim(coalesce(p_valor, '')),
            '[[:space:]]+',
            ' ',
            'g'
        )
    );
$$;

-- Soma somente a parcela líquida ainda válida dos apontamentos da requisição.
create function public.fn_quantidade_entregue_liquida(
    p_item_requisicao_id bigint
)
returns numeric
language sql
stable
set search_path = public
as $$
    select coalesce(
        sum(
            greatest(
                ae.quantidade_entregue
                - coalesce(devolucao.quantidade_devolvida, 0),
                0
            )
        ),
        0
    )::numeric(14, 3)
    from public.apontamentos_entrega ae
    left join lateral (
        select coalesce(sum(de.quantidade_devolvida), 0)
            as quantidade_devolvida
        from public.devolucoes_entrega de
        where de.apontamento_entrega_id = ae.id
    ) devolucao on true
    where ae.item_requisicao_id = p_item_requisicao_id;
$$;

-- ============================================================================
-- 5. RPC: IMPORTAÇÃO DO E-MAIL
--    Aceita tanto o payload atual em inglês quanto as chaves em português.
-- ============================================================================

create function public.importar_email(
    p_email jsonb,
    p_itens_requisicao jsonb,
    p_itens_resumo jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_importacao_id bigint;
    v_id_existente bigint;

    v_hash_arquivo text;
    v_nome_arquivo text;
    v_assunto text;
    v_remetente text;
    v_recebido_em text;
    v_local_estoque text;
    v_tipo_movimento text;
    v_importado_por text;

    v_item jsonb;

    v_quantidade_detalhes integer;
    v_quantidade_resumos integer;
    v_peso_detalhes numeric(14, 3);
    v_peso_resumos numeric(14, 3);
begin
    v_hash_arquivo := coalesce(
        nullif(p_email->>'hash_arquivo', ''),
        nullif(p_email->>'file_hash', '')
    );

    v_nome_arquivo := coalesce(
        nullif(p_email->>'nome_arquivo', ''),
        nullif(p_email->>'file_name', '')
    );

    v_assunto := coalesce(
        p_email->>'assunto',
        p_email->>'subject'
    );

    v_remetente := coalesce(
        p_email->>'remetente',
        p_email->>'sender'
    );

    v_recebido_em := coalesce(
        nullif(p_email->>'recebido_em', ''),
        nullif(p_email->>'received_at', '')
    );

    v_local_estoque := upper(coalesce(
        nullif(p_email->>'local_estoque', ''),
        nullif(p_email->>'stock_location', ''),
        ''
    ));

    v_tipo_movimento := coalesce(
        p_email->>'tipo_movimento',
        p_email->>'movement_type'
    );

    v_importado_por := coalesce(
        p_email->>'importado_por',
        p_email->>'imported_by'
    );

    if v_hash_arquivo is null then
        raise exception 'O payload do e-mail não contém o hash do arquivo.';
    end if;

    if v_nome_arquivo is null then
        raise exception 'O payload do e-mail não contém o nome do arquivo.';
    end if;

    insert into public.importacoes_email (
        hash_arquivo,
        nome_arquivo,
        assunto,
        remetente,
        recebido_em,
        local_estoque,
        tipo_movimento,
        importado_por
    )
    values (
        v_hash_arquivo,
        v_nome_arquivo,
        v_assunto,
        v_remetente,
        v_recebido_em::timestamptz,
        nullif(v_local_estoque, ''),
        v_tipo_movimento,
        v_importado_por
    )
    on conflict (hash_arquivo) do nothing
    returning id into v_importacao_id;

    if v_importacao_id is null then
        select id
        into v_id_existente
        from public.importacoes_email
        where hash_arquivo = v_hash_arquivo;

        return jsonb_build_object(
            'status', 'DUPLICADO',
            'importacao_id', v_id_existente
        );
    end if;

    for v_item in
        select value
        from jsonb_array_elements(
            coalesce(p_itens_requisicao, '[]'::jsonb)
        )
    loop
        insert into public.itens_requisicao (
            importacao_email_id,
            tipo_material,
            local_estoque,
            material,
            dimensao,
            quantidade,
            rastreabilidade,
            data_requisicao,
            maquina,
            localizacao,
            setor,
            peso_material_kg,
            peso_requisitado_kg,
            indice_tabela_origem,
            indice_linha_origem
        )
        values (
            v_importacao_id,
            coalesce(
                nullif(v_item->>'tipo_material', ''),
                nullif(v_item->>'material_type', ''),
                'NAO_INFORMADO'
            ),
            upper(coalesce(
                nullif(v_item->>'local_estoque', ''),
                nullif(v_item->>'stock_location', ''),
                nullif(v_local_estoque, ''),
                'NAO_INFORMADO'
            )),
            coalesce(v_item->>'material', ''),
            coalesce(v_item->>'dimensao', v_item->>'dimension', ''),
            coalesce(
                nullif(v_item->>'quantidade', '')::numeric,
                nullif(v_item->>'quantity', '')::numeric,
                0
            ),
            coalesce(v_item->>'rastreabilidade', v_item->>'traceability', ''),
            nullif(coalesce(
                v_item->>'data_requisicao',
                v_item->>'request_date',
                ''
            ), '')::date,
            coalesce(v_item->>'maquina', v_item->>'machine', ''),
            coalesce(v_item->>'localizacao', v_item->>'location', ''),
            coalesce(v_item->>'setor', v_item->>'sector', ''),
            coalesce(
                nullif(v_item->>'peso_material_kg', '')::numeric,
                nullif(v_item->>'material_weight_kg', '')::numeric
            ),
            coalesce(
                nullif(v_item->>'peso_requisitado_kg', '')::numeric,
                nullif(v_item->>'requested_weight_kg', '')::numeric
            ),
            coalesce(
                nullif(v_item->>'indice_tabela_origem', '')::integer,
                nullif(v_item->>'source_table_index', '')::integer
            ),
            coalesce(
                nullif(v_item->>'indice_linha_origem', '')::integer,
                nullif(v_item->>'source_row_index', '')::integer
            )
        );
    end loop;

    for v_item in
        select value
        from jsonb_array_elements(
            coalesce(p_itens_resumo, '[]'::jsonb)
        )
    loop
        insert into public.itens_resumo_totvs (
            importacao_email_id,
            tipo_material,
            local_estoque,
            numero_requisicao,
            material,
            os_so,
            numero_of,
            peso_material_kg,
            peso_requisitado_kg,
            indice_tabela_origem,
            indice_linha_origem
        )
        values (
            v_importacao_id,
            coalesce(
                nullif(v_item->>'tipo_material', ''),
                nullif(v_item->>'material_type', ''),
                'NAO_INFORMADO'
            ),
            upper(coalesce(
                nullif(v_item->>'local_estoque', ''),
                nullif(v_item->>'stock_location', ''),
                nullif(v_local_estoque, ''),
                'NAO_INFORMADO'
            )),
            coalesce(v_item->>'numero_requisicao', v_item->>'request_number', ''),
            coalesce(v_item->>'material', ''),
            coalesce(v_item->>'os_so', ''),
            coalesce(v_item->>'numero_of', v_item->>'of_number', ''),
            coalesce(
                nullif(v_item->>'peso_material_kg', '')::numeric,
                nullif(v_item->>'material_weight_kg', '')::numeric
            ),
            coalesce(
                nullif(v_item->>'peso_requisitado_kg', '')::numeric,
                nullif(v_item->>'requested_weight_kg', '')::numeric
            ),
            coalesce(
                nullif(v_item->>'indice_tabela_origem', '')::integer,
                nullif(v_item->>'source_table_index', '')::integer
            ),
            coalesce(
                nullif(v_item->>'indice_linha_origem', '')::integer,
                nullif(v_item->>'source_row_index', '')::integer
            )
        );
    end loop;

    select
        count(*),
        coalesce(sum(peso_requisitado_kg), 0)
    into
        v_quantidade_detalhes,
        v_peso_detalhes
    from public.itens_requisicao
    where importacao_email_id = v_importacao_id;

    select
        count(*),
        coalesce(sum(peso_requisitado_kg), 0)
    into
        v_quantidade_resumos,
        v_peso_resumos
    from public.itens_resumo_totvs
    where importacao_email_id = v_importacao_id;

    update public.importacoes_email
    set
        quantidade_detalhes = v_quantidade_detalhes,
        quantidade_resumos = v_quantidade_resumos,
        peso_detalhes = v_peso_detalhes,
        peso_resumos = v_peso_resumos
    where id = v_importacao_id;

    return jsonb_build_object(
        'status', 'IMPORTADO',
        'importacao_id', v_importacao_id,
        'quantidade_detalhes', v_quantidade_detalhes,
        'quantidade_resumos', v_quantidade_resumos,
        'peso_detalhes', v_peso_detalhes,
        'peso_resumos', v_peso_resumos
    );
end;
$$;

-- ============================================================================
-- 6. RPC: ENTREGA NORMAL / MATERIAL NOVO
-- ============================================================================

create function public.registrar_entrega(
    p_item_requisicao_id bigint,
    p_quantidade numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_solicitada numeric(14, 3);
    v_quantidade_ja_entregue numeric(14, 3);
    v_quantidade_restante numeric(14, 3);
    v_quantidade_aplicada numeric(14, 3);
    v_quantidade_excedente numeric(14, 3);
    v_material text;
    v_rastreabilidade text;
    v_local_estoque text;
    v_apontamento_id bigint;
begin
    if p_quantidade is null or p_quantidade <= 0 then
        raise exception 'A quantidade entregue deve ser maior que zero.';
    end if;

    if nullif(btrim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select
        ir.quantidade,
        ir.material,
        ir.rastreabilidade,
        ir.local_estoque
    into
        v_quantidade_solicitada,
        v_material,
        v_rastreabilidade,
        v_local_estoque
    from public.itens_requisicao ir
    where ir.id = p_item_requisicao_id
    for update;

    if not found then
        raise exception 'Item de requisição não encontrado.';
    end if;

    if upper(coalesce(v_local_estoque, '')) <> 'EST' then
        raise exception 'Somente itens EST recebem apontamento de entrega.';
    end if;

    v_quantidade_ja_entregue :=
        public.fn_quantidade_entregue_liquida(p_item_requisicao_id);

    v_quantidade_restante := greatest(
        v_quantidade_solicitada - v_quantidade_ja_entregue,
        0
    );

    if v_quantidade_restante <= 0 then
        raise exception 'A requisição já está totalmente atendida.';
    end if;

    v_quantidade_aplicada := least(p_quantidade, v_quantidade_restante);
    v_quantidade_excedente := greatest(
        p_quantidade - v_quantidade_aplicada,
        0
    );

    if v_quantidade_excedente > 0
       and (
            nullif(btrim(v_material), '') is null
            or nullif(btrim(v_rastreabilidade), '') is null
       ) then
        raise exception
            'Não é possível registrar excedente sem material e rastreabilidade.';
    end if;

    insert into public.apontamentos_entrega (
        item_requisicao_id,
        quantidade_entregue,
        quantidade_excedente,
        origem_entrega,
        nome_operador,
        observacao
    )
    values (
        p_item_requisicao_id,
        v_quantidade_aplicada,
        v_quantidade_excedente,
        'NOVO',
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), '')
    )
    returning id into v_apontamento_id;

    if v_quantidade_excedente > 0 then
        insert into public.lotes_materiais_fabrica (
            apontamento_origem_id,
            material,
            material_chave,
            rastreabilidade,
            rastreabilidade_chave,
            quantidade_inicial,
            quantidade_disponivel,
            nome_operador
        )
        values (
            v_apontamento_id,
            btrim(v_material),
            public.fn_chave_material(v_material),
            btrim(v_rastreabilidade),
            public.fn_chave_material(v_rastreabilidade),
            v_quantidade_excedente,
            v_quantidade_excedente,
            btrim(p_nome_operador)
        );
    end if;

    return jsonb_build_object(
        'status', 'REGISTRADO',
        'apontamento_entrega_id', v_apontamento_id,
        'quantidade_informada', p_quantidade,
        'quantidade_aplicada', v_quantidade_aplicada,
        'quantidade_excedente', v_quantidade_excedente,
        'quantidade_restante', greatest(
            v_quantidade_restante - v_quantidade_aplicada,
            0
        )
    );
end;
$$;

-- ============================================================================
-- 7. RPC: CONSULTAR MATERIAL EM FÁBRICA
-- ============================================================================

create function public.consultar_material_fabrica(
    p_item_requisicao_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_material text;
    v_rastreabilidade text;
    v_quantidade_solicitada numeric(14, 3);
    v_quantidade_entregue numeric(14, 3);
    v_quantidade_disponivel numeric(14, 3);
begin
    select
        ir.material,
        ir.rastreabilidade,
        ir.quantidade
    into
        v_material,
        v_rastreabilidade,
        v_quantidade_solicitada
    from public.itens_requisicao ir
    where ir.id = p_item_requisicao_id;

    if not found then
        raise exception 'Item de requisição não encontrado.';
    end if;

    v_quantidade_entregue :=
        public.fn_quantidade_entregue_liquida(p_item_requisicao_id);

    select coalesce(sum(lmf.quantidade_disponivel), 0)
    into v_quantidade_disponivel
    from public.lotes_materiais_fabrica lmf
    where lmf.material_chave = public.fn_chave_material(v_material)
      and lmf.rastreabilidade_chave = public.fn_chave_material(v_rastreabilidade)
      and lmf.quantidade_disponivel > 0;

    return jsonb_build_object(
        'item_requisicao_id', p_item_requisicao_id,
        'material', v_material,
        'rastreabilidade', v_rastreabilidade,
        'quantidade_restante_requisicao', greatest(
            v_quantidade_solicitada - v_quantidade_entregue,
            0
        ),
        'quantidade_disponivel', v_quantidade_disponivel
    );
end;
$$;

-- ============================================================================
-- 8. RPC: ENTREGA PARCIAL USANDO SOMENTE MATERIAL DA FÁBRICA
-- ============================================================================

create function public.registrar_entrega_material_fabrica(
    p_item_requisicao_id bigint,
    p_quantidade_fabrica numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_solicitada numeric(14, 3);
    v_quantidade_entregue numeric(14, 3);
    v_quantidade_restante numeric(14, 3);
    v_quantidade_disponivel numeric(14, 3);
    v_material text;
    v_rastreabilidade text;
    v_local_estoque text;
    v_apontamento_id bigint;
    v_faltante numeric(14, 3);
    v_consumir numeric(14, 3);
    v_lote record;
begin
    if p_quantidade_fabrica is null or p_quantidade_fabrica <= 0 then
        raise exception 'A quantidade da fábrica deve ser maior que zero.';
    end if;

    if nullif(btrim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select
        ir.quantidade,
        ir.material,
        ir.rastreabilidade,
        ir.local_estoque
    into
        v_quantidade_solicitada,
        v_material,
        v_rastreabilidade,
        v_local_estoque
    from public.itens_requisicao ir
    where ir.id = p_item_requisicao_id
    for update;

    if not found then
        raise exception 'Item de requisição não encontrado.';
    end if;

    if upper(coalesce(v_local_estoque, '')) <> 'EST' then
        raise exception 'Somente itens EST recebem apontamento de entrega.';
    end if;

    if nullif(btrim(v_material), '') is null
       or nullif(btrim(v_rastreabilidade), '') is null then
        raise exception 'A requisição precisa ter material e rastreabilidade.';
    end if;

    v_quantidade_entregue :=
        public.fn_quantidade_entregue_liquida(p_item_requisicao_id);

    v_quantidade_restante := greatest(
        v_quantidade_solicitada - v_quantidade_entregue,
        0
    );

    if v_quantidade_restante <= 0 then
        raise exception 'A requisição já está totalmente atendida.';
    end if;

    if p_quantidade_fabrica > v_quantidade_restante then
        raise exception
            'A quantidade da fábrica (%) é maior que o restante da requisição (%).',
            p_quantidade_fabrica,
            v_quantidade_restante;
    end if;

    -- Bloqueia todos os lotes candidatos antes de validar o saldo.
    select coalesce(sum(lote.quantidade_disponivel), 0)
    into v_quantidade_disponivel
    from (
        select
            lmf.id,
            lmf.quantidade_disponivel
        from public.lotes_materiais_fabrica lmf
        where lmf.material_chave = public.fn_chave_material(v_material)
          and lmf.rastreabilidade_chave = public.fn_chave_material(v_rastreabilidade)
          and lmf.quantidade_disponivel > 0
        order by lmf.recebido_em, lmf.id
        for update
    ) lote;

    if p_quantidade_fabrica > v_quantidade_disponivel then
        raise exception
            'Saldo em fábrica insuficiente. Disponível: %.',
            v_quantidade_disponivel;
    end if;

    insert into public.apontamentos_entrega (
        item_requisicao_id,
        quantidade_entregue,
        quantidade_excedente,
        origem_entrega,
        nome_operador,
        observacao
    )
    values (
        p_item_requisicao_id,
        p_quantidade_fabrica,
        0,
        'FABRICA',
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), '')
    )
    returning id into v_apontamento_id;

    v_faltante := p_quantidade_fabrica;

    for v_lote in
        select
            lmf.id,
            lmf.quantidade_disponivel
        from public.lotes_materiais_fabrica lmf
        where lmf.material_chave = public.fn_chave_material(v_material)
          and lmf.rastreabilidade_chave = public.fn_chave_material(v_rastreabilidade)
          and lmf.quantidade_disponivel > 0
        order by lmf.recebido_em, lmf.id
        for update
    loop
        exit when v_faltante <= 0;

        v_consumir := least(v_lote.quantidade_disponivel, v_faltante);

        update public.lotes_materiais_fabrica
        set quantidade_disponivel = quantidade_disponivel - v_consumir
        where id = v_lote.id;

        insert into public.consumos_materiais_fabrica (
            lote_material_fabrica_id,
            apontamento_destino_id,
            quantidade_consumida,
            quantidade_estornada,
            nome_operador
        )
        values (
            v_lote.id,
            v_apontamento_id,
            v_consumir,
            0,
            btrim(p_nome_operador)
        );

        v_faltante := v_faltante - v_consumir;
    end loop;

    if v_faltante > 0 then
        raise exception
            'O saldo em fábrica foi alterado por outro usuário. Tente novamente.';
    end if;

    return jsonb_build_object(
        'status', 'REGISTRADO_FABRICA',
        'apontamento_entrega_id', v_apontamento_id,
        'quantidade_fabrica', p_quantidade_fabrica,
        'quantidade_nova_aplicada', 0,
        'quantidade_excedente', 0,
        'quantidade_restante', greatest(
            v_quantidade_restante - p_quantidade_fabrica,
            0
        )
    );
end;
$$;

-- ============================================================================
-- 9. RPC: ENTREGA MISTA
--    Usa todo o saldo possível da fábrica e depois o material novo informado.
-- ============================================================================

create function public.registrar_entrega_mista(
    p_item_requisicao_id bigint,
    p_quantidade_nova numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_solicitada numeric(14, 3);
    v_quantidade_entregue numeric(14, 3);
    v_quantidade_restante numeric(14, 3);
    v_quantidade_disponivel numeric(14, 3);
    v_quantidade_fabrica numeric(14, 3);
    v_restante_apos_fabrica numeric(14, 3);
    v_quantidade_nova_aplicada numeric(14, 3);
    v_quantidade_excedente numeric(14, 3);
    v_material text;
    v_rastreabilidade text;
    v_local_estoque text;
    v_apontamento_fabrica_id bigint;
    v_apontamento_novo_id bigint;
    v_faltante numeric(14, 3);
    v_consumir numeric(14, 3);
    v_lote record;
begin
    if p_quantidade_nova is null or p_quantidade_nova <= 0 then
        raise exception 'A quantidade de material novo deve ser maior que zero.';
    end if;

    if nullif(btrim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select
        ir.quantidade,
        ir.material,
        ir.rastreabilidade,
        ir.local_estoque
    into
        v_quantidade_solicitada,
        v_material,
        v_rastreabilidade,
        v_local_estoque
    from public.itens_requisicao ir
    where ir.id = p_item_requisicao_id
    for update;

    if not found then
        raise exception 'Item de requisição não encontrado.';
    end if;

    if upper(coalesce(v_local_estoque, '')) <> 'EST' then
        raise exception 'Somente itens EST recebem apontamento de entrega.';
    end if;

    if nullif(btrim(v_material), '') is null
       or nullif(btrim(v_rastreabilidade), '') is null then
        raise exception 'A requisição precisa ter material e rastreabilidade.';
    end if;

    v_quantidade_entregue :=
        public.fn_quantidade_entregue_liquida(p_item_requisicao_id);

    v_quantidade_restante := greatest(
        v_quantidade_solicitada - v_quantidade_entregue,
        0
    );

    if v_quantidade_restante <= 0 then
        raise exception 'A requisição já está totalmente atendida.';
    end if;

    -- Bloqueia todos os lotes candidatos antes de calcular o saldo.
    select coalesce(sum(lote.quantidade_disponivel), 0)
    into v_quantidade_disponivel
    from (
        select
            lmf.id,
            lmf.quantidade_disponivel
        from public.lotes_materiais_fabrica lmf
        where lmf.material_chave = public.fn_chave_material(v_material)
          and lmf.rastreabilidade_chave = public.fn_chave_material(v_rastreabilidade)
          and lmf.quantidade_disponivel > 0
        order by lmf.recebido_em, lmf.id
        for update
    ) lote;

    v_quantidade_fabrica := least(
        v_quantidade_disponivel,
        v_quantidade_restante
    );

    if v_quantidade_fabrica <= 0 then
        raise exception 'Não há saldo deste material e rastreabilidade na fábrica.';
    end if;

    v_restante_apos_fabrica :=
        v_quantidade_restante - v_quantidade_fabrica;

    if v_restante_apos_fabrica <= 0 then
        raise exception
            'O saldo em fábrica já atende toda a requisição. Use a opção Somente fábrica.';
    end if;

    v_quantidade_nova_aplicada := least(
        p_quantidade_nova,
        v_restante_apos_fabrica
    );

    v_quantidade_excedente := greatest(
        p_quantidade_nova - v_quantidade_nova_aplicada,
        0
    );

    -- Primeiro apontamento: parcela reaproveitada da fábrica.
    insert into public.apontamentos_entrega (
        item_requisicao_id,
        quantidade_entregue,
        quantidade_excedente,
        origem_entrega,
        nome_operador,
        observacao
    )
    values (
        p_item_requisicao_id,
        v_quantidade_fabrica,
        0,
        'FABRICA',
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), '')
    )
    returning id into v_apontamento_fabrica_id;

    v_faltante := v_quantidade_fabrica;

    for v_lote in
        select
            lmf.id,
            lmf.quantidade_disponivel
        from public.lotes_materiais_fabrica lmf
        where lmf.material_chave = public.fn_chave_material(v_material)
          and lmf.rastreabilidade_chave = public.fn_chave_material(v_rastreabilidade)
          and lmf.quantidade_disponivel > 0
        order by lmf.recebido_em, lmf.id
        for update
    loop
        exit when v_faltante <= 0;

        v_consumir := least(v_lote.quantidade_disponivel, v_faltante);

        update public.lotes_materiais_fabrica
        set quantidade_disponivel = quantidade_disponivel - v_consumir
        where id = v_lote.id;

        insert into public.consumos_materiais_fabrica (
            lote_material_fabrica_id,
            apontamento_destino_id,
            quantidade_consumida,
            quantidade_estornada,
            nome_operador
        )
        values (
            v_lote.id,
            v_apontamento_fabrica_id,
            v_consumir,
            0,
            btrim(p_nome_operador)
        );

        v_faltante := v_faltante - v_consumir;
    end loop;

    if v_faltante > 0 then
        raise exception
            'O saldo em fábrica foi alterado por outro usuário. Tente novamente.';
    end if;

    -- Segundo apontamento: material novo enviado pelo estoque.
    insert into public.apontamentos_entrega (
        item_requisicao_id,
        quantidade_entregue,
        quantidade_excedente,
        origem_entrega,
        nome_operador,
        observacao
    )
    values (
        p_item_requisicao_id,
        v_quantidade_nova_aplicada,
        v_quantidade_excedente,
        'NOVO',
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), '')
    )
    returning id into v_apontamento_novo_id;

    if v_quantidade_excedente > 0 then
        insert into public.lotes_materiais_fabrica (
            apontamento_origem_id,
            material,
            material_chave,
            rastreabilidade,
            rastreabilidade_chave,
            quantidade_inicial,
            quantidade_disponivel,
            nome_operador
        )
        values (
            v_apontamento_novo_id,
            btrim(v_material),
            public.fn_chave_material(v_material),
            btrim(v_rastreabilidade),
            public.fn_chave_material(v_rastreabilidade),
            v_quantidade_excedente,
            v_quantidade_excedente,
            btrim(p_nome_operador)
        );
    end if;

    return jsonb_build_object(
        'status', 'REGISTRADO_MISTO',
        'apontamento_fabrica_id', v_apontamento_fabrica_id,
        'apontamento_novo_id', v_apontamento_novo_id,
        'quantidade_fabrica', v_quantidade_fabrica,
        'quantidade_nova_aplicada', v_quantidade_nova_aplicada,
        'quantidade_excedente', v_quantidade_excedente,
        'quantidade_restante', greatest(
            v_quantidade_restante
            - v_quantidade_fabrica
            - v_quantidade_nova_aplicada,
            0
        )
    );
end;
$$;

-- ============================================================================
-- 10. RPC: AJUSTAR MANUALMENTE O SALDO DE UM LOTE
-- ============================================================================

create function public.ajustar_material_fabrica(
    p_lote_material_fabrica_id bigint,
    p_nova_quantidade numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_anterior numeric(14, 3);
begin
    if p_nova_quantidade is null or p_nova_quantidade < 0 then
        raise exception 'A nova quantidade não pode ser negativa.';
    end if;

    if nullif(btrim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select quantidade_disponivel
    into v_quantidade_anterior
    from public.lotes_materiais_fabrica
    where id = p_lote_material_fabrica_id
    for update;

    if not found then
        raise exception 'Lote de material em fábrica não encontrado.';
    end if;

    update public.lotes_materiais_fabrica
    set quantidade_disponivel = p_nova_quantidade
    where id = p_lote_material_fabrica_id;

    insert into public.ajustes_materiais_fabrica (
        lote_material_fabrica_id,
        quantidade_anterior,
        quantidade_nova,
        diferenca,
        nome_operador,
        observacao,
        motivo
    )
    values (
        p_lote_material_fabrica_id,
        v_quantidade_anterior,
        p_nova_quantidade,
        p_nova_quantidade - v_quantidade_anterior,
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), ''),
        'AJUSTE_MANUAL'
    );

    return jsonb_build_object(
        'status', 'AJUSTADO',
        'lote_material_fabrica_id', p_lote_material_fabrica_id,
        'quantidade_anterior', v_quantidade_anterior,
        'quantidade_nova', p_nova_quantidade,
        'oculto_da_tela', p_nova_quantidade = 0
    );
end;
$$;

-- ============================================================================
-- 11. RPC: DEVOLUÇÃO
--     FABRICA: devolve a quantidade aos lotes consumidos.
--     NOVO: se a entrega for totalmente devolvida, zera o excedente disponível.
-- ============================================================================

create function public.devolver_material(
    p_apontamento_entrega_id bigint,
    p_quantidade numeric,
    p_nome_operador text,
    p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantidade_original numeric(14, 3);
    v_quantidade_excedente numeric(14, 3);
    v_quantidade_ja_devolvida numeric(14, 3);
    v_quantidade_disponivel_devolucao numeric(14, 3);
    v_quantidade_restante_apontamento numeric(14, 3);
    v_origem_entrega text;
    v_devolucao_id bigint;

    v_a_estornar numeric(14, 3);
    v_estornar numeric(14, 3);
    v_consumo record;
    v_lote record;
begin
    if p_quantidade is null or p_quantidade <= 0 then
        raise exception 'A quantidade devolvida deve ser maior que zero.';
    end if;

    if nullif(btrim(p_nome_operador), '') is null then
        raise exception 'Informe o operador responsável.';
    end if;

    select
        ae.quantidade_entregue,
        ae.quantidade_excedente,
        ae.origem_entrega
    into
        v_quantidade_original,
        v_quantidade_excedente,
        v_origem_entrega
    from public.apontamentos_entrega ae
    where ae.id = p_apontamento_entrega_id
    for update;

    if not found then
        raise exception 'Apontamento de entrega não encontrado.';
    end if;

    select coalesce(sum(de.quantidade_devolvida), 0)
    into v_quantidade_ja_devolvida
    from public.devolucoes_entrega de
    where de.apontamento_entrega_id = p_apontamento_entrega_id;

    v_quantidade_disponivel_devolucao :=
        v_quantidade_original - v_quantidade_ja_devolvida;

    if p_quantidade > v_quantidade_disponivel_devolucao then
        raise exception
            'A quantidade informada (%) é maior que a disponível para devolução (%).',
            p_quantidade,
            v_quantidade_disponivel_devolucao;
    end if;

    insert into public.devolucoes_entrega (
        apontamento_entrega_id,
        quantidade_devolvida,
        nome_operador,
        observacao
    )
    values (
        p_apontamento_entrega_id,
        p_quantidade,
        btrim(p_nome_operador),
        nullif(btrim(p_observacao), '')
    )
    returning id into v_devolucao_id;

    v_quantidade_restante_apontamento :=
        v_quantidade_disponivel_devolucao - p_quantidade;

    -- Uma devolução de material reaproveitado retorna aos mesmos lotes.
    if v_origem_entrega = 'FABRICA' then
        v_a_estornar := p_quantidade;

        for v_consumo in
            select
                cmf.id,
                cmf.lote_material_fabrica_id,
                cmf.quantidade_consumida - cmf.quantidade_estornada
                    as quantidade_restauravel
            from public.consumos_materiais_fabrica cmf
            where cmf.apontamento_destino_id = p_apontamento_entrega_id
              and cmf.quantidade_consumida - cmf.quantidade_estornada > 0
            order by cmf.id desc
            for update
        loop
            exit when v_a_estornar <= 0;

            v_estornar := least(
                v_consumo.quantidade_restauravel,
                v_a_estornar
            );

            update public.consumos_materiais_fabrica
            set quantidade_estornada = quantidade_estornada + v_estornar
            where id = v_consumo.id;

            -- Bloqueia o lote antes de devolver o saldo.
            perform 1
            from public.lotes_materiais_fabrica
            where id = v_consumo.lote_material_fabrica_id
            for update;

            update public.lotes_materiais_fabrica
            set quantidade_disponivel = quantidade_disponivel + v_estornar
            where id = v_consumo.lote_material_fabrica_id;

            v_a_estornar := v_a_estornar - v_estornar;
        end loop;

        if v_a_estornar > 0 then
            raise exception
                'Inconsistência no consumo dos lotes. Não foi possível estornar %.',
                v_a_estornar;
        end if;
    end if;

    -- Se a entrega NOVA foi totalmente devolvida, remove da fábrica todo o
    -- excedente dessa entrega que ainda não tinha sido consumido.
    if v_origem_entrega = 'NOVO'
       and v_quantidade_restante_apontamento <= 0
       and v_quantidade_excedente > 0 then
        for v_lote in
            select
                lmf.id,
                lmf.quantidade_disponivel
            from public.lotes_materiais_fabrica lmf
            where lmf.apontamento_origem_id = p_apontamento_entrega_id
              and lmf.quantidade_disponivel > 0
            for update
        loop
            insert into public.ajustes_materiais_fabrica (
                lote_material_fabrica_id,
                quantidade_anterior,
                quantidade_nova,
                diferenca,
                nome_operador,
                observacao,
                motivo
            )
            values (
                v_lote.id,
                v_lote.quantidade_disponivel,
                0,
                -v_lote.quantidade_disponivel,
                btrim(p_nome_operador),
                coalesce(
                    nullif(btrim(p_observacao), ''),
                    'Excedente removido após devolução total da entrega.'
                ),
                'DEVOLUCAO_TOTAL_DA_ENTREGA'
            );

            update public.lotes_materiais_fabrica
            set quantidade_disponivel = 0
            where id = v_lote.id;
        end loop;
    end if;

    return jsonb_build_object(
        'status', 'DEVOLVIDO',
        'devolucao_id', v_devolucao_id,
        'apontamento_entrega_id', p_apontamento_entrega_id,
        'quantidade_devolvida', p_quantidade,
        'quantidade_entregue_restante', v_quantidade_restante_apontamento,
        'origem_entrega', v_origem_entrega
    );
end;
$$;

-- ============================================================================
-- 12. VIEWS DA APLICAÇÃO
-- ============================================================================

create view public.vw_progresso_requisicoes as
select
    ir.id as item_requisicao_id,
    ir.importacao_email_id,
    ir.tipo_material,
    ir.local_estoque,
    ir.material,
    ir.dimensao,

    ir.quantidade as quantidade_solicitada,

    coalesce(movimento.quantidade_entregue, 0)::numeric(14, 3)
        as quantidade_entregue,

    greatest(
        ir.quantidade - coalesce(movimento.quantidade_entregue, 0),
        0
    )::numeric(14, 3) as quantidade_restante,

    case
        when upper(ir.local_estoque) = 'FAB'
            then 'NAO_REQUER_ENTREGA'
        when ir.quantidade - coalesce(movimento.quantidade_entregue, 0) <= 0
            then 'ENTREGUE'
        when coalesce(movimento.quantidade_entregue, 0) > 0
            then 'PARCIAL'
        else 'PENDENTE'
    end as status_entrega,

    ir.rastreabilidade,
    ir.data_requisicao,
    ir.maquina,
    ir.localizacao,
    ir.setor,
    ir.peso_material_kg,
    ir.peso_requisitado_kg,

    case
        when upper(ir.local_estoque) = 'EST'
         and ir.quantidade - coalesce(movimento.quantidade_entregue, 0) <= 0
            then movimento.ultima_entrega_em
        else null
    end as concluido_em,

    ie.nome_arquivo as nome_arquivo_email,
    ie.assunto as assunto_email,
    ie.recebido_em as recebido_em_email,
    ie.tipo_movimento

from public.itens_requisicao ir
join public.importacoes_email ie
  on ie.id = ir.importacao_email_id
left join lateral (
    select
        coalesce(
            sum(
                greatest(
                    ae.quantidade_entregue
                    - coalesce(devolucao.quantidade_devolvida, 0),
                    0
                )
            ),
            0
        ) as quantidade_entregue,
        max(ae.entregue_em) as ultima_entrega_em
    from public.apontamentos_entrega ae
    left join lateral (
        select coalesce(sum(de.quantidade_devolvida), 0)
            as quantidade_devolvida
        from public.devolucoes_entrega de
        where de.apontamento_entrega_id = ae.id
    ) devolucao on true
    where ae.item_requisicao_id = ir.id
) movimento on true;

create view public.vw_pendencias_est_operador as
select *
from public.vw_progresso_requisicoes
where upper(local_estoque) = 'EST'
  and quantidade_restante > 0;

create view public.vw_requisicoes_administrativo as
select *
from public.vw_progresso_requisicoes
where upper(local_estoque) = 'FAB'
   or (
        upper(local_estoque) = 'EST'
        and quantidade_restante <= 0
   );

-- Uma linha por apontamento de entrega.
create view public.vw_historico_entregas as
select
    ae.id as apontamento_entrega_id,
    ir.id as item_requisicao_id,
    ir.importacao_email_id,

    ir.data_requisicao,
    ie.recebido_em as recebido_em_email,
    ae.entregue_em,

    ir.material,
    ir.dimensao,
    ir.quantidade as quantidade_solicitada,

    ae.quantidade_entregue::numeric(14, 3)
        as quantidade_entregue_original,

    coalesce(devolucao.quantidade_devolvida, 0)::numeric(14, 3)
        as quantidade_devolvida,

    greatest(
        ae.quantidade_entregue
        - coalesce(devolucao.quantidade_devolvida, 0),
        0
    )::numeric(14, 3) as quantidade_entregue,

    ae.quantidade_excedente::numeric(14, 3)
        as quantidade_excedente,

    ae.origem_entrega,

    ir.rastreabilidade,
    ir.localizacao,
    ir.setor,

    ae.nome_operador,
    ae.observacao,

    case
        when coalesce(devolucao.quantidade_devolvida, 0) = 0
            then 'ENTREGUE'
        when ae.quantidade_entregue
             - coalesce(devolucao.quantidade_devolvida, 0) <= 0
            then 'DEVOLVIDO'
        else 'DEVOLVIDO_PARCIAL'
    end as status_apontamento,

    devolucao.ultima_devolucao_em

from public.apontamentos_entrega ae
join public.itens_requisicao ir
  on ir.id = ae.item_requisicao_id
join public.importacoes_email ie
  on ie.id = ir.importacao_email_id
left join lateral (
    select
        coalesce(sum(de.quantidade_devolvida), 0)
            as quantidade_devolvida,
        max(de.devolvido_em) as ultima_devolucao_em
    from public.devolucoes_entrega de
    where de.apontamento_entrega_id = ae.id
) devolucao on true
where upper(ir.local_estoque) = 'EST';

-- Uma linha por devolução realizada.
create view public.vw_historico_devolucoes as
select
    de.id as devolucao_id,
    de.apontamento_entrega_id,
    ir.id as item_requisicao_id,

    ir.data_requisicao,
    ie.recebido_em as recebido_em_email,
    ae.entregue_em,
    de.devolvido_em,

    ir.material,
    ir.dimensao,

    ae.quantidade_entregue::numeric(14, 3)
        as quantidade_entregue_original,
    de.quantidade_devolvida::numeric(14, 3)
        as quantidade_devolvida,

    ir.rastreabilidade,
    ir.localizacao,
    ir.setor,

    de.nome_operador as operador_devolucao,
    de.observacao as observacao_devolucao,
    ae.nome_operador as operador_entrega,

    ae.origem_entrega,
    ae.quantidade_excedente::numeric(14, 3)
        as quantidade_excedente

from public.devolucoes_entrega de
join public.apontamentos_entrega ae
  on ae.id = de.apontamento_entrega_id
join public.itens_requisicao ir
  on ir.id = ae.item_requisicao_id
join public.importacoes_email ie
  on ie.id = ir.importacao_email_id;

-- Tela de consulta dos lotes que ainda possuem saldo.
create view public.vw_materiais_fabrica as
select
    lmf.id as lote_material_fabrica_id,
    lmf.apontamento_origem_id,
    lmf.recebido_em,
    lmf.material,
    lmf.rastreabilidade,
    lmf.quantidade_inicial,
    lmf.quantidade_disponivel,
    lmf.nome_operador
from public.lotes_materiais_fabrica lmf
where lmf.quantidade_disponivel > 0;

-- ============================================================================
-- 13. PERMISSÕES PARA O CLIENTE SUPABASE
-- ============================================================================

grant usage on schema public to anon, authenticated;

alter table public.importacoes_email disable row level security;
alter table public.itens_requisicao disable row level security;
alter table public.itens_resumo_totvs disable row level security;
alter table public.apontamentos_entrega disable row level security;
alter table public.devolucoes_entrega disable row level security;
alter table public.lotes_materiais_fabrica disable row level security;
alter table public.consumos_materiais_fabrica disable row level security;
alter table public.ajustes_materiais_fabrica disable row level security;

grant select, insert, update, delete
    on public.importacoes_email,
       public.itens_requisicao,
       public.itens_resumo_totvs,
       public.apontamentos_entrega,
       public.devolucoes_entrega,
       public.lotes_materiais_fabrica,
       public.consumos_materiais_fabrica,
       public.ajustes_materiais_fabrica
    to anon, authenticated;

grant select
    on public.vw_progresso_requisicoes,
       public.vw_pendencias_est_operador,
       public.vw_requisicoes_administrativo,
       public.vw_historico_entregas,
       public.vw_historico_devolucoes,
       public.vw_materiais_fabrica
    to anon, authenticated;

grant usage, select
    on all sequences in schema public
    to anon, authenticated;

-- Remove a permissão automática de execução para papéis não explicitados.
revoke all on function public.importar_email(jsonb, jsonb, jsonb) from public;
revoke all on function public.registrar_entrega(bigint, numeric, text, text) from public;
revoke all on function public.consultar_material_fabrica(bigint) from public;
revoke all on function public.registrar_entrega_material_fabrica(bigint, numeric, text, text) from public;
revoke all on function public.registrar_entrega_mista(bigint, numeric, text, text) from public;
revoke all on function public.ajustar_material_fabrica(bigint, numeric, text, text) from public;
revoke all on function public.devolver_material(bigint, numeric, text, text) from public;

grant execute
    on function public.importar_email(jsonb, jsonb, jsonb),
       public.registrar_entrega(bigint, numeric, text, text),
       public.consultar_material_fabrica(bigint),
       public.registrar_entrega_material_fabrica(bigint, numeric, text, text),
       public.registrar_entrega_mista(bigint, numeric, text, text),
       public.ajustar_material_fabrica(bigint, numeric, text, text),
       public.devolver_material(bigint, numeric, text, text)
    to anon, authenticated;

commit;
